# Intro 2 Python  - Numpy


![](https://www.saturdays.ai/images/logo.png)

In [ ]:
# Que nunca se nos olvide el import

import numpy as np  

### Arrays preparados dara usar

* Array de ceros `np.zeros(shape)`
* Array de ceros `np.zeros_like(array)`
* Array de unos `np.ones(shape)`
* Array de unos `np.ones_like(shape)`
* Array lleno de un número `np.full(shape,numero)`
* Array lleno de un número `np.full_like(array,numero)`
* Matriz identidad `np.eye(numerofilas)`
* Array de números aleatorios (uniforme) `np.random.random(size)`
* Array de números aleatorios (distrib normal) `np.random.normal(centro,disp,size)`

In [1]:
mi_array = np.array([1,3,4,5,6])
np.zeros_like(mi_array)
np.zeros((8,))

NameError: name 'np' is not defined

In [ ]:
mi_array = np.array([1,3,4,5,6])
np.ones_like(mi_array)
np.ones((10,))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full((3,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random((3,4))

array([[0.85933024, 0.16303665, 0.55085082, 0.52944364],
       [0.06991723, 0.90352886, 0.15459016, 0.00117796],
       [0.73197458, 0.99564912, 0.73041161, 0.57676683]])

In [ ]:
np.random.normal(0,1,(3,4))

array([[ 0.34234181,  0.97575768,  0.4689392 ,  0.13735295],
       [ 0.08529486,  0.25068691, -0.92781867, -1.76064252],
       [-1.11265544, -1.89096786, -0.12902122,  0.33010418]])

### Acceso a través de índices


Al igual que con las listas, se puede acceder a las distintas posiciones tanto individuales como a secciones

In [ ]:
# elementos individuales

In [ ]:
mi_array = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
print(mi_array)
print(mi_array.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)


In [ ]:
mi_array[1,0]

5

In [ ]:
mi_array[0,:]

array([0, 1, 2, 3, 4])

In [ ]:
mi_array[-1,:]

array([10, 11, 12, 13, 14])

In [ ]:
mi_array[:3,2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [ ]:
mi_array[:,1]

array([ 1,  6, 11])