![](https://www.saturdays.ai/images/logo.png)

# Intro 2 Python  - Numpy


In [ ]:
# Que nunca se nos olvide el import
import numpy as np  

### Operaciones aritméticas básicas

Para arrays del mismo tamaño:

* Suma `a + b`
* Resta `a - b`
* Multiplicación por elementos `a * b`
* División `a / b`


In [ ]:
a = np.array([6,1,9])
b = np.full(3,2)

In [ ]:
a/b

array([3. , 0.5, 4.5])

### Operaciones estadísticas y de vectores

Estadísticas

* Media `np.mean(a)`
* Desviación estandar `np.std(a)`
* Mediana `np.median(a)`

Con vectores

* Producto escalar `np.dot(a,b)`
* Suma de elementos `a.sum()`
* Sumar las filas  `a.sum(axis = 1)`
* Sumar las columnas  `a.sum(axis = 0)`


In [ ]:
mi_array = np.random.random((3,4))

In [ ]:
mi_array

array([[0.75046524, 0.54176721, 0.71764824, 0.76971246],
       [0.27275081, 0.51352685, 0.24379497, 0.06524855],
       [0.01777266, 0.74252864, 0.21803877, 0.73694733]])

In [ ]:
np.median(mi_array)

0.5276470328051627

In [ ]:
mi_array_2 = np.random.random((4,5))

In [ ]:
np.dot(mi_array,mi_array_2)

array([[0.85217918, 1.46535531, 1.37874094, 1.02637171, 0.85619185],
       [0.36150996, 0.55129808, 0.42752325, 0.40321349, 0.27992164],
       [0.23766385, 1.07933943, 0.6768332 , 0.48301879, 0.73177968]])

In [ ]:
print(mi_array_2)

[[0.85179073 0.38467588 0.74740579 0.42653358 0.19783548]
 [0.21338234 0.58665473 0.19415478 0.26796243 0.33470785]
 [0.06206048 0.39522672 0.34735739 0.55589093 0.0516962 ]
 [0.06859536 0.74729903 0.60200632 0.21068344 0.63567865]]


In [ ]:
mi_array_2.sum(axis=0)

array([1.19582891, 2.11385636, 1.89092428, 1.46107039, 1.21991817])

### Broadcasting

Permite operar con arrays de distintas dimensiones. Internamente, se ajustan los tamaños para operar


In [ ]:
print(mi_array_2 * 100)

[[85.17907293 38.46758799 74.74057857 42.65335849 19.78354826]
 [21.33823408 58.66547304 19.41547754 26.79624274 33.47078482]
 [ 6.20604769 39.52267158 34.73573943 55.5890934   5.16961958]
 [ 6.85953626 74.72990333 60.20063226 21.06834436 63.56786474]]


In [ ]:
asdf = np.full((4,5),100)
mi_array_2 * asdf

array([[85.17907293, 38.46758799, 74.74057857, 42.65335849, 19.78354826],
       [21.33823408, 58.66547304, 19.41547754, 26.79624274, 33.47078482],
       [ 6.20604769, 39.52267158, 34.73573943, 55.5890934 ,  5.16961958],
       [ 6.85953626, 74.72990333, 60.20063226, 21.06834436, 63.56786474]])

La regla general es que cualquier dimensión que sea 1, se "alarga" para poder operar

In [ ]:
asdf = np.full((4,1),2)
mi_array_2 * asdf

array([[1.70358146, 0.76935176, 1.49481157, 0.85306717, 0.39567097],
       [0.42676468, 1.17330946, 0.38830955, 0.53592485, 0.6694157 ],
       [0.12412095, 0.79045343, 0.69471479, 1.11178187, 0.10339239],
       [0.13719073, 1.49459807, 1.20401265, 0.42136689, 1.27135729]])